version = 1

exclude_patterns = [
    "vendor/*",
    "tools/vendor/*"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/obalunenko/instadiff-cli"]
  dependencies_vendored = true

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
