  ignoreGeneratedHeader = true
    severity = "warning"
    # Sets the default failure confidence. This means that linting errors
    # with less than 0.8 confidence will be ignored.
    confidence = 0.0

    # Sets the error code for failures with severity "error"
    errorCode = 0

    # Sets the error code for failures with severity "warning"
    warningCode = 0

    [rule.blank-imports]
    [rule.context-as-argument]
    [rule.context-keys-type]
    [rule.dot-imports]
    [rule.error-return]
    [rule.error-strings]
    [rule.error-naming]
    [rule.exported]
    [rule.if-return]
    [rule.increment-decrement]
    [rule.var-declaration]
    [rule.package-comments]
    [rule.range]
    [rule.receiver-naming]
    [rule.time-naming]
    [rule.unexported-return]
    [rule.indent-error-flow]
    [rule.errorf]
    [rule.argument-limit]
      arguments =[4]

    [rule.atomic]
    [rule.bare-return]
    [rule.bool-literal-in-expr]
    [rule.call-to-gc]
    [rule.confusing-naming]
    [rule.confusing-results]
    [rule.constant-logical-expr]
    [rule.cyclomatic]
      arguments =[10]

    [rule.deep-exit]
    [rule.duplicated-imports]
    [rule.empty-block]
    [rule.empty-lines]
    [rule.flag-parameter]
    [rule.function-result-limit]
      arguments =[3]

    [rule.get-return]

    [rule.import-shadowing]
    [rule.line-length-limit]
      arguments =[120]

    [rule.max-public-structs]
      arguments =[3]

    [rule.modifies-parameter]
    [rule.modifies-value-receiver]

    [rule.range-val-in-closure]

    [rule.redefines-builtin-id]
    [rule.struct-tag]
    [rule.superfluous-else]


    [rule.unhandled-error]
      arguments =["fmt.Printf", "fmt.Println"]
    [rule.unnecessary-stmt]
    [rule.unreachable-code]
    [rule.unused-parameter]
    [rule.unused-receiver]
    [rule.waitgroup-by-value]
